/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library;

import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joene
 */
public class GetCatalogStudent extends javax.swing.JFrame {

    /**
     * Creates new form GetCatalogStudent
     */
    public GetCatalogStudent() {
        initComponents();
        
         try {
            Class.forName("com.mysql.jdbc.Driver");
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/TestInfo", "root", "")) {
                String sql = "SELECT * FROM CatalogBook"; 
                PreparedStatement pst = con.prepareStatement(sql);
                

                ResultSet rs = pst.executeQuery();

                DefaultTableModel tb1Model = (DefaultTableModel) jTable2.getModel();
                tb1Model.setRowCount(0); // Clear existing table data

                while (rs.next()) {
                    String ISBN = rs.getString("isbn");
                    String AccessionNumber = rs.getString("accesionnumber");
                    String CallNumber = rs.getString("callnumber");
                    String Title = rs.getString("title");
                    String Author = rs.getString("author");
                    String Edition = rs.getString("edition");
                    String Volume = rs.getString("volume");
                    String Pages = rs.getString("pages");
                    String Copyright = rs.getString("copyright");
                    String SourceofFund = rs.getString("sourceoffund");
                    String Publisher = rs.getString("publisher");
                    String PlaceofPublication = rs.getString("placeofpublication");
                    String Classification = rs.getString("classification");
                    String LibraryCopies = rs.getString("librarycopies");
                    String Remarks = rs.getString("remarks");

                    String[] tbData = {ISBN, AccessionNumber, CallNumber, Title, Author, Edition, Volume, Pages, Copyright, SourceofFund, Publisher, PlaceofPublication, Classification, LibraryCopies, Remarks};
                    tb1Model.addRow(tbData);
                }
            }
        }

        catch (ClassNotFoundException e) {
            System.out.println("Error loading MySQL JDBC driver: " + e.getMessage());
        }

        catch (SQLException e) {
            System.out.println("Error connecting to the database: " + e.getMessage());
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        catalogInput = new javax.swing.JTextField();
        SearchBtn1 = new javax.swing.JButton();
        SearchBtn2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTable2.setBackground(new java.awt.Color(0, 255, 255));
        jTable2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Accession Number", "Call Number", "Title", "Author", "Edition", "Volume", "Pages", "Copyright", "Source of Fund", "Publisher", "Place of Publication", "Classification", "Library Copies", "Remarks"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setGridColor(new java.awt.Color(0, 0, 0));
        jTable2.setRowHeight(35);
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable2.setShowGrid(true);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable2MouseEntered(evt);
            }
        });
        jTable2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable2KeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(1).setMinWidth(50);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTable2.getColumnModel().getColumn(1).setMaxWidth(50);
            jTable2.getColumnModel().getColumn(3).setMinWidth(200);
            jTable2.getColumnModel().getColumn(3).setPreferredWidth(200);
            jTable2.getColumnModel().getColumn(3).setMaxWidth(200);
            jTable2.getColumnModel().getColumn(5).setMinWidth(70);
            jTable2.getColumnModel().getColumn(5).setPreferredWidth(70);
            jTable2.getColumnModel().getColumn(5).setMaxWidth(70);
            jTable2.getColumnModel().getColumn(6).setMinWidth(40);
            jTable2.getColumnModel().getColumn(6).setPreferredWidth(40);
            jTable2.getColumnModel().getColumn(6).setMaxWidth(40);
            jTable2.getColumnModel().getColumn(7).setMinWidth(40);
            jTable2.getColumnModel().getColumn(7).setPreferredWidth(40);
            jTable2.getColumnModel().getColumn(7).setMaxWidth(40);
            jTable2.getColumnModel().getColumn(8).setMinWidth(50);
            jTable2.getColumnModel().getColumn(8).setPreferredWidth(50);
            jTable2.getColumnModel().getColumn(8).setMaxWidth(50);
            jTable2.getColumnModel().getColumn(9).setMinWidth(70);
            jTable2.getColumnModel().getColumn(9).setPreferredWidth(70);
            jTable2.getColumnModel().getColumn(9).setMaxWidth(70);
            jTable2.getColumnModel().getColumn(12).setMinWidth(50);
            jTable2.getColumnModel().getColumn(12).setPreferredWidth(50);
            jTable2.getColumnModel().getColumn(12).setMaxWidth(50);
            jTable2.getColumnModel().getColumn(13).setMinWidth(40);
            jTable2.getColumnModel().getColumn(13).setPreferredWidth(40);
            jTable2.getColumnModel().getColumn(13).setMaxWidth(40);
            jTable2.getColumnModel().getColumn(14).setMinWidth(50);
            jTable2.getColumnModel().getColumn(14).setPreferredWidth(50);
            jTable2.getColumnModel().getColumn(14).setMaxWidth(50);
        }

        catalogInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalogInputActionPerformed(evt);
            }
        });
        catalogInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                catalogInputKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                catalogInputKeyReleased(evt);
            }
        });

        SearchBtn1.setBackground(java.awt.Color.blue);
        SearchBtn1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        SearchBtn1.setForeground(java.awt.Color.white);
        SearchBtn1.setText("Search");
        SearchBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtn1ActionPerformed(evt);
            }
        });

        SearchBtn2.setBackground(java.awt.Color.black);
        SearchBtn2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        SearchBtn2.setForeground(java.awt.Color.white);
        SearchBtn2.setText("Back");
        SearchBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(1345, Short.MAX_VALUE)
                .addComponent(SearchBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(catalogInput, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(SearchBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(944, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(catalogInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SearchBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(701, 701, 701)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseEntered

    private void jTable2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable2KeyReleased

    }//GEN-LAST:event_jTable2KeyReleased

    private void catalogInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalogInputActionPerformed

    }//GEN-LAST:event_catalogInputActionPerformed

    private void catalogInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_catalogInputKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_catalogInputKeyPressed

    private void catalogInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_catalogInputKeyReleased

        String searchText = catalogInput.getText().trim();
        String sql = "SELECT * FROM CatalogBook WHERE LOWER(title) LIKE '%"+searchText.toLowerCase()+"%' OR LOWER(author) LIKE '%"+searchText.toLowerCase()+"%' OR LOWER(copyright) LIKE '%"+searchText.toLowerCase()+"%'";
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/TestInfo", "root", "");
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery()) {

            DefaultTableModel tb1Model = (DefaultTableModel) jTable2.getModel();
            tb1Model.setRowCount(0);

            while (rs.next()) {
                String ISBN = rs.getString("isbn");
                String AccessionNumber = rs.getString("accesionnumber");
                String CallNumber = rs.getString("callnumber");
                String Title = rs.getString("title");
                String Author = rs.getString("author");
                String Edition = rs.getString("edition");
                String Volume = rs.getString("volume");
                String Pages = rs.getString("pages");
                String Copyright = rs.getString("copyright");
                String SourceofFund = rs.getString("sourceoffund");
                String Publisher = rs.getString("publisher");
                String PlaceofPublication = rs.getString("placeofpublication");
                String Classification = rs.getString("classification");
                String LibraryCopies = rs.getString("librarycopies");
                String Remarks = rs.getString("remarks");

                String[] tbData = {ISBN, AccessionNumber, CallNumber, Title, Author, Edition, Volume, Pages, Copyright, SourceofFund, Publisher, PlaceofPublication, Classification, LibraryCopies, Remarks};
                tb1Model.addRow(tbData);

            }
        }

        catch (SQLException e) {
            System.out.println("Error connecting to the database: " + e.getMessage());
        }

        catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_catalogInputKeyReleased

    private void SearchBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtn1ActionPerformed

    }//GEN-LAST:event_SearchBtn1ActionPerformed

    private void SearchBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtn2ActionPerformed

   

    }//GEN-LAST:event_SearchBtn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GetCatalogStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GetCatalogStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GetCatalogStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GetCatalogStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GetCatalogStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SearchBtn1;
    private javax.swing.JButton SearchBtn2;
    private javax.swing.JTextField catalogInput;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
